name: borlago
description: BorlaGo app for requesters

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  get_it: ^7.6.0
  google_fonts: ^4.0.5
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.6
  flutter_native_splash: ^2.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/images/